// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKAPH03QM8zxYDmD1hH83Fe81yIB-rHwk',
    appId: '1:490831937136:web:9f9fa48007085a44ad3eb5',
    messagingSenderId: '490831937136',
    projectId: 'educationapp-c1cb9',
    authDomain: 'educationapp-c1cb9.firebaseapp.com',
    storageBucket: 'educationapp-c1cb9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdCtkW7QEBaqfJT5qFVFJc9IgW3WABMr4',
    appId: '1:490831937136:android:ae80c4be3c92af69ad3eb5',
    messagingSenderId: '490831937136',
    projectId: 'educationapp-c1cb9',
    storageBucket: 'educationapp-c1cb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfpAH3U0Ouq4L5pFZHCZYdNrtffnkks_o',
    appId: '1:490831937136:ios:af9dd51e01df5861ad3eb5',
    messagingSenderId: '490831937136',
    projectId: 'educationapp-c1cb9',
    storageBucket: 'educationapp-c1cb9.firebasestorage.app',
    iosBundleId: 'com.example.educationalForChildren',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfpAH3U0Ouq4L5pFZHCZYdNrtffnkks_o',
    appId: '1:490831937136:ios:af9dd51e01df5861ad3eb5',
    messagingSenderId: '490831937136',
    projectId: 'educationapp-c1cb9',
    storageBucket: 'educationapp-c1cb9.firebasestorage.app',
    iosBundleId: 'com.example.educationalForChildren',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKAPH03QM8zxYDmD1hH83Fe81yIB-rHwk',
    appId: '1:490831937136:web:4e848a301c9ade77ad3eb5',
    messagingSenderId: '490831937136',
    projectId: 'educationapp-c1cb9',
    authDomain: 'educationapp-c1cb9.firebaseapp.com',
    storageBucket: 'educationapp-c1cb9.firebasestorage.app',
  );
}
